### ISSUE TITLE
Why no no work 

### ISSUE THREAD

**Issue by Jeremy5909** [SinaKhalili/Folders.py#6]
i typed "Folders helloworld"
```
Traceback (most recent call last):
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\Scripts\Folders.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'folders'
```

**Comment by SinaKhalili** [comment]
whoops looks like I broke it trying to setup github actions, will fix

**Comment by Jeremy5909** [comment]
fix it mr.

**Comment by Jeremy5909** [comment]
> whoops looks like I broke it trying to setup github actions, will fix

uhh I updated to 0.0.6 and it still giving same message

**Comment by SinaKhalili** [comment]
yeye I'll update u when it works just trying some stuff out

**Comment by SinaKhalili** [comment]
@Jeremy5909  can u try re-installing now (0.0.8), lmk how it goes

**Comment by Jeremy5909** [comment]
> @Jeremy5909 can u try re-installing now (0.0.8), lmk how it goes

thanks bbg working good
